name: Terraform Unit Tests

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - "modules/**/**.tf"
      - ".tflint.hcl"
      - ".github/workflows/terraform-test.yml"

jobs:
  build:
    name: Run Terraform Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3
      - run: terraform fmt -check=true -diff=true -recursive
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.55.1
      - name: Terraform Init
        run: terraform init -backend=false
      - name: Terraform Validate
        run: terraform validate
      - name: Run TFLint
        run: make lint
